Test.Name = "Test"
Test.ScreenInsets = Enum.ScreenInsets.CoreUISafeInsets
Test.DisplayOrder = 0
Test.SafeAreaCompatibility = Enum.SafeAreaCompatibility.FullscreenExtension
Test.ClipToDeviceSafeArea = true
Test.Parent = game.CoreGui

MainFrame.Name = "MainFrame"
MainFrame.NextSelectionLeft = nil
MainFrame.Active = false
MainFrame.Interactable = true
MainFrame.AnchorPoint = Vector2.new(0.5, 0.5)
MainFrame.NextSelectionRight = nil
MainFrame.ZIndex = 1
MainFrame.AutomaticSize = Enum.AutomaticSize.None
MainFrame.Size = UDim2.new(0, 300, 0, 200)
MainFrame.Visible = true
MainFrame.SizeConstraint = Enum.SizeConstraint.RelativeXY
MainFrame.SelectionOrder = 0
MainFrame.NextSelectionDown = nil
MainFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
MainFrame.SelectionImageObject = nil
MainFrame.Selectable = false
MainFrame.LayoutOrder = 0
MainFrame.Rotation = 0
MainFrame.ClipsDescendants = false
MainFrame.BackgroundTransparency = 0
MainFrame.Position = UDim2.new(0.5, 0, 0.5, 0)
MainFrame.NextSelectionUp = nil
MainFrame.BorderMode = Enum.BorderMode.Outline
MainFrame.BorderSizePixel = 0
MainFrame.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
MainFrame.Style = Enum.FrameStyle.Custom
MainFrame.Parent = Test

Label1.Name = "Label1"
Label1.NextSelectionLeft = nil
Label1.Active = false
Label1.Interactable = true
Label1.AnchorPoint = Vector2.new(0, 0)
Label1.NextSelectionRight = nil
Label1.ZIndex = 1
Label1.AutomaticSize = Enum.AutomaticSize.None
Label1.Size = UDim2.new(0, 200, 0, 50)
Label1.Visible = true
Label1.SizeConstraint = Enum.SizeConstraint.RelativeXY
Label1.SelectionOrder = 0
Label1.NextSelectionDown = nil
Label1.BorderColor3 = Color3.fromRGB(0, 0, 0)
Label1.SelectionImageObject = nil
Label1.Selectable = false
Label1.LayoutOrder = 0
Label1.Rotation = 0
Label1.ClipsDescendants = false
Label1.BackgroundTransparency = 0
Label1.Position = UDim2.new(0.166666672, 0, 0.0399999991, 0)
Label1.NextSelectionUp = nil
Label1.BorderMode = Enum.BorderMode.Outline
Label1.BorderSizePixel = 0
Label1.BackgroundColor3 = Color3.fromRGB(100, 100, 100)
Label1.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Label1.TextDirection = Enum.TextDirection.Auto
Label1.TextTransparency = 0
Label1.OpenTypeFeatures = ""
Label1.TextStrokeTransparency = 1
Label1.TextTruncate = Enum.TextTruncate.None
Label1.TextSize = 14
Label1.RichText = false
Label1.TextColor3 = Color3.fromRGB(0, 0, 0)
Label1.Text = "Label"
Label1.TextYAlignment = Enum.TextYAlignment.Center
Label1.LineHeight = 1
Label1.TextXAlignment = Enum.TextXAlignment.Center
Label1.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
Label1.MaxVisibleGraphemes = -1
Label1.TextScaled = false
Label1.TextWrapped = false
Label1.Parent = MainFrame

Label2.Name = "Label2"
Label2.NextSelectionLeft = nil
Label2.Active = false
Label2.Interactable = true
Label2.AnchorPoint = Vector2.new(0, 0)
Label2.NextSelectionRight = nil
Label2.ZIndex = 1
Label2.AutomaticSize = Enum.AutomaticSize.None
Label2.Size = UDim2.new(0, 200, 0, 50)
Label2.Visible = true
Label2.SizeConstraint = Enum.SizeConstraint.RelativeXY
Label2.SelectionOrder = 0
Label2.NextSelectionDown = nil
Label2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Label2.SelectionImageObject = nil
Label2.Selectable = false
Label2.LayoutOrder = 0
Label2.Rotation = 0
Label2.ClipsDescendants = false
Label2.BackgroundTransparency = 0
Label2.Position = UDim2.new(0.166666672, 0, 0.289999992, 0)
Label2.NextSelectionUp = nil
Label2.BorderMode = Enum.BorderMode.Outline
Label2.BorderSizePixel = 0
Label2.BackgroundColor3 = Color3.fromRGB(100, 100, 100)
Label2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Label2.TextDirection = Enum.TextDirection.Auto
Label2.TextTransparency = 0
Label2.OpenTypeFeatures = ""
Label2.TextStrokeTransparency = 1
Label2.TextTruncate = Enum.TextTruncate.None
Label2.TextSize = 14
Label2.RichText = false
Label2.TextColor3 = Color3.fromRGB(0, 0, 0)
Label2.Text = "Label"
Label2.TextYAlignment = Enum.TextYAlignment.Center
Label2.LineHeight = 1
Label2.TextXAlignment = Enum.TextXAlignment.Center
Label2.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
Label2.MaxVisibleGraphemes = -1
Label2.TextScaled = false
Label2.TextWrapped = false
Label2.Parent = MainFrame

Label3.Name = "Label3"
Label3.NextSelectionLeft = nil
Label3.Active = false
Label3.Interactable = true
Label3.AnchorPoint = Vector2.new(0, 0)
Label3.NextSelectionRight = nil
Label3.ZIndex = 1
Label3.AutomaticSize = Enum.AutomaticSize.None
Label3.Size = UDim2.new(0, 200, 0, 50)
Label3.Visible = true
Label3.SizeConstraint = Enum.SizeConstraint.RelativeXY
Label3.SelectionOrder = 0
Label3.NextSelectionDown = nil
Label3.BorderColor3 = Color3.fromRGB(0, 0, 0)
Label3.SelectionImageObject = nil
Label3.Selectable = false
Label3.LayoutOrder = 0
Label3.Rotation = 0
Label3.ClipsDescendants = false
Label3.BackgroundTransparency = 0
Label3.Position = UDim2.new(0.166666672, 0, 0.540000021, 0)
Label3.NextSelectionUp = nil
Label3.BorderMode = Enum.BorderMode.Outline
Label3.BorderSizePixel = 0
Label3.BackgroundColor3 = Color3.fromRGB(100, 100, 100)
Label3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Label3.TextDirection = Enum.TextDirection.Auto
Label3.TextTransparency = 0
Label3.OpenTypeFeatures = ""
Label3.TextStrokeTransparency = 1
Label3.TextTruncate = Enum.TextTruncate.None
Label3.TextSize = 14
Label3.RichText = false
Label3.TextColor3 = Color3.fromRGB(0, 0, 0)
Label3.Text = "Label"
Label3.TextYAlignment = Enum.TextYAlignment.Center
Label3.LineHeight = 1
Label3.TextXAlignment = Enum.TextXAlignment.Center
Label3.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
Label3.MaxVisibleGraphemes = -1
Label3.TextScaled = false
Label3.TextWrapped = false
Label3.Parent = MainFrame
